title: Laboratory Standard Operating Procedure (SOP)
description: Targeted Amplicon Deep Sequencing of Plasmodium falciparum molecular markers of resistance
show_downloads: True
google_analytics: G-S8XG5V75W1

theme: jekyll-theme-leap-day
gem "github-pages", group: :jekyll_plugins
